### ISSUE TITLE
Enhancement: Smaller, more readable JSON style property encoding

### ISSUE THREAD

**Issue by Danny-Alexander** [steffen-kiess/factorio-BlueprintAlignment#1]
How about using: 

`Some blueprint {align:[16,8]}`
to shorten
`Some blueprint (alignx = 16, aligny = 8)`

and

`Some blueprint {align:[16,8,0,0,10,10]}`
to shorten
`Some blueprint (alignx = 16, aligny = 8, offsetx = 0, offsety = 0, roffsetx = 10, roffsety = 10)`
?

**Pros:**
- much shorter and arguably more readable
- can use generic json parser to build properties object from the text beginning at the first '{'.
   - _(it's not strictly well formed json without quotes around the keys but many parsers including the javascript one work with this format, apparently)_
- simple to encode additional properties with less compatibility risk.
    - _it would be easy to encode info for other mods in the name without them interfering with each other using json syntax that is familiar to many people._

**Cons:** 
- `:` may cause issues if saving blueprints using their name as the filename.
    - _Workaround: allow using `;` as well (replace before parse) - it looks almost the same and causes no issues with file system._
- not strictly well formed json so may break if javascript parser changes to be strict.
    - _Workaround: allow using quotes and use regex to insert missing quotes after top level `{` and before next `:` before parsing._

You could even separate property decoding into another module or mod even for other blueprint mods to use. 

I'd just like a shorter name without reducing readability or simplicity though, which I think a JSON style would give with other benefits too.

**Comment by steffen-kiess** [comment]
> Some blueprint {align:[16,8,0,0,10,10]}

The disadvantage here is that it is no longer clear what "0, 0" means.

In the current version of the mod (0.0.2, released just now), there is now a UI for changing the properties and the properties are stored in a special entity in the blueprint, i.e. the label doesn't have to be changed at all. IMHO this is a lot nicer anyway. The old way of storing the information in the label is still available, but I'm not sure whether adding a third method to store the information would be a good idea. If someone really prefers storing stuff in the label, I probably could add a method to store it as JSON (or almost-JSON) in the label.

**Comment by steffen-kiess** [comment]
I think storing the data as an entity is preferable to storing it in the label.

**Comment by Danny-Alexander** [comment]
Just saw this. I agree that's better still. Thanks for comments & apologies for late reply.
